output_path: 
  outlines: "output/outlines/"
  chapters: "output/chapters/"
  edits: "output/edits/"
model_parameters:
  model_name: "deepseek-r1:14b"
  max_tokens: 2048
  temperature: 0.7
  top_p: 0.9
  frequency_penalty: 0
  presence_penalty: 0